In [4]:
import pickle
import joblib

hyberik results Shape

In [10]:
file = r"C:\Users\PC\Desktop\workingSpace\KPT2SkAnimEval\dataset\out\hyberik_bates\SMPLPoss_000000.pkl"

data = joblib.load(file)
print(data.keys())

for key in data.keys():
    print(key, data[key].shape)

dict_keys(['smpl_pose', 'smpl_trans', 'smpl_scaling'])
smpl_pose (116, 72)
smpl_trans (3,)
smpl_scaling (1,)


smplify3d results Shape

In [11]:
file = r"C:\Users\PC\Desktop\workingSpace\KPT2SkAnimEval\dataset\out\smplify3d_bates\results_smplfitting_bates\SMPLFit_000000\SMPLPose_000000.pkl"

data = joblib.load(file)
print(data.keys())

for key in data.keys():
    print(key, data[key].shape)

dict_keys(['smpl_pose', 'smpl_trans', 'smpl_scaling'])
smpl_pose (116, 72)
smpl_trans (116, 3)
smpl_scaling (1,)


Chek 52 points

In [12]:
import numpy as np

In [13]:
file = r'C:\Users\PC\Desktop\workingSpace\KPT2SkAnimEval\dataset\52point\S01C01B01.json.npy'
data52point = np.load(file)
print(data52point.shape) 

(210, 52, 3)


In [14]:
print(data52point[0])

[[ 0.07986649  0.31661316  2.20533618]
 [ 0.17258409  0.31147989  2.1911897 ]
 [-0.00374105  0.32124207  2.21809253]
 [ 0.08372049  0.40808133  2.19740491]
 [ 0.16627789 -0.09767306  2.1398877 ]
 [ 0.02731783 -0.08558744  2.27498779]
 [ 0.08757448  0.4995495   2.18947363]
 [ 0.17194148 -0.44587723  2.32444604]
 [ 0.06642262 -0.46989676  2.37195386]
 [ 0.08928559  0.68426682  2.17762708]
 [ 0.16820432 -0.5902934   2.19648462]
 [ 0.04021635 -0.56751935  2.22597437]
 [ 0.09099671  0.86898413  2.16578052]
 [ 0.17493134  0.73610182  2.15017438]
 [ 0.00976157  0.73500496  2.1779339 ]
 [ 0.08747491  0.95146509  2.1494812 ]
 [ 0.26057709  0.78793683  2.12272168]
 [-0.06976246  0.7857431   2.17824072]
 [ 0.30928424  0.50772983  2.13500391]
 [-0.12256999  0.5160589   2.27106494]
 [ 0.2921214   0.27334946  2.0918938 ]
 [-0.12776688  0.28087949  2.2144502 ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.        